package org.skyluc.neki_site.yaml

object YamlKeys {
  val BAND = "band"
  val CHRONOLOGYPAGE = "chronologypage"
  val CONTENT = "content"
  val HIGHLIGHT = "highlight"
  val INSTAGRAM = "instagram"
  val LINK = "link"
  val MAIN = "main"
  val MUSIC = "music"
  val MUSICPAGE = "musicpage"
  val NAVIGATION = "navigation"
  val NEWS = "news"
  val PAGE = "page"
  val ROLE = "role"
  val SITE = "site"
  val SHOWSPAGE = "showspage"
  val SOCIAL_MEDIA = "social-media"
  val SUPPORT = "support"
  val TIKTOK = "tiktok"
  val TITLE = "title"
  val X = "x"
  val YOUTUBE = "youtube"
}
