collections:
  song:
    output: true
    permalink: /song/:name.html
  song_extra:
    output: true
    permalink: /song/extra/:name.html
  album:
    output: true
    permalink: /album/:name.html
  album_extra:
    output: true
    permalink: /album/extra/:name.html
  show:
    output: true
    premalink: /show:path.html

# dark pages. Usually not fully publicly released information

  d_song:
    output: true
    permalink: /dark/song/:name.html

# previous location of files, not the canonical ones since February 2025

  old_songs:
    output: true
    permalink: /songs/:name.html
  old_concerts:
    output: true
    permalink: /concerts/:name.html
  old_albums:
    output: true
    permalink: /albums/:name.html

exclude: ["README.md", "**/README.md", "tmp/", "Gemfile*", "NOT_REFERENCED.md", "TODO", "**/NP_*"]
include: [.well-known]

defaults:
  - scope:
      path: ""
      type: "song"
    values:
      layout: "song"
  - scope:
      path: ""
      type: "song_extra"
    values:
      layout: "song_extra"
  - scope:
      path: ""
      type: "album"
    values:
      layout: "album"
  - scope:
      path: ""
      type: "album_extra"
    values:
      layout: "album_extra"
  - scope:
      path: ""
      type: "show"
    values:
      layout: "show"
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: ""
      type: "d_song"
    values:
      layout: "d_song"

# previous location of files, not the canonical ones since February 2025
  - scope:
      path: ""
      type: "old_songs"
    values:
      layout: "song"
  - scope:
      path: ""
      type: "old_concerts"
    values:
      layout: "show"
  - scope:
      path: ""
      type: "old_albums"
    values:
      layout: "album"



domain: neki-fan-resources.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: "https://neki-fan-resources.github.io"  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: ""   