- name: Band
  elements:
  - label: Band logo
    description: from band YouTube page
    url: https://www.youtube.com/@neki_official/
  - label: Band picture
    description: frame from Get Over official music video
    url: https://www.youtube.com/watch?v=TWbLqba3oag
  - label: Social media logos
    description: their respective website
- name: Music
  pages:
  - name: Get Over
    elements:
    - label: Cover image
      description: YouTube community post
      url: https://www.youtube.com/post/Ugkxre_r-CJix3Q2mb5CwU1eOZEbRH-8nv3X
    - label: Credits
      description: "song info on Deezer"
      url: https://www.deezer.com/us/artist/260920991/top_track
    - label: Original lyrics
      description: from YouTube Official Music Video description
      url: https://www.youtube.com/watch?v=TWbLqba3oag
    - label: Lyrics english translation
      description: from YouTube Official Music Video subtitles
      url: https://www.youtube.com/watch?v=TWbLqba3oag
  - name: 令現少女
    elements:
    - label: Cover image
      description: YouTube community post
      url: https://www.youtube.com/post/UgkxS1rZMadPjbT3oNLv97mTgd9W_joqBM-A
    - label: Credits
      description: "JASRAC - work ID: 303-5428-5"
      url: https://www2.jasrac.or.jp/
    - label: Original lyrics
      description: from YouTube Official Music Video subtitles
      url: https://www.youtube.com/watch?v=rq0dca9mFfI
    - label: Lyrics english translation
      description: from YouTube Official Music Video subtitles
      url: https://www.youtube.com/watch?v=rq0dca9mFfI
  - name: MAZE
    elements:
    - label: Cover image
      description: YouTube community post
      url: https://www.youtube.com/post/Ugkxi0lwEh-cjiRo3Mly4Ihc5SG4PLQY7RiV
    - label: Credits
      description: "JASRAC - work ID: 304-0228-0"
      url: https://www2.jasrac.or.jp/
    - label: Original lyrics
      description: from YouTube Official Music Video subtitles
      url: https://www.youtube.com/watch?v=EHtWJmMybGY
    - label: Lyrics english translation
      description: from YouTube Official Music Video subtitles
      url: https://www.youtube.com/watch?v=EHtWJmMybGY
  - name: ENDLESSGAME
    elements:
    - label: Cover image
      description: YouTube community post
      url: https://www.youtube.com/post/Ugkx0AQkkFZtBcrkKnhuMQF2ougpm9YttR4V
    - label: Credits
      description: "JASRAC - work ID: 303-5429-3"
      url: https://www2.jasrac.or.jp/
    - label: Original lyrics
      description: from EXCLAMAT!ON EP booklet
  - name: Blink
    elements:
    - label: Cover image
      description: YouTube community post
      url: https://www.youtube.com/post/Ugkx0AQkkFZtBcrkKnhuMQF2ougpm9YttR4V
    - label: Credits
      description: "JASRAC - work ID: 303-5430-7"
      url: https://www2.jasrac.or.jp/
    - label: lyrics transciption used for comparison
      description: youtube comment on Blink
      url: https://www.youtube.com/watch?v=oyVxBskxRJw&lc=UgynSXtrdBY6L7uftLB4AaABAg&ab_channel=NEK%21-Topic
    - label: lyrics transciption used for comparison
      description: metalsapphire web site
      url: https://www.metalsapphire.com/NEKI/Songs.html#Blink
  - name: Loner
    elements:
    - label: Cover image
      description: YouTube community post
      url: https://www.youtube.com/post/UgkxUTduxcQGkcCJWaYYDzHNVGzyhCTRtCut
    - label: Credits
      description: "JASRAC - work ID: 790-9145-8"
      url: https://www2.jasrac.or.jp/
    - label: Original lyrics
      description: from YouTube Official Music Video subtitles
      url: https://www.youtube.com/watch?v=uhy1HnFXTH8
    - label: Lyrics english translation
      description: from YouTube Official Music Video subtitles
      url: https://www.youtube.com/watch?v=uhy1HnFXTH8
  - name: Dreams!!!
    elements:
    - label: Cover image
      description: YouTube community post
      url: https://www.youtube.com/post/UgkxQKc7C0ISVO2Q-n7kOhzCPRL5MkpkqlHT
    - label: Credits
      description: "song info on Deezer"
      url: https://www.deezer.com/us/artist/260920991/top_track
    - label: Original lyrics
      description: from YouTube Official Live Video subtitles
      url: https://www.youtube.com/watch?v=_Oac92XPkyo
    - label: Lyrics english translation
      description: from YouTube Official Live Video subtitles
      url: https://www.youtube.com/watch?v=_Oac92XPkyo
  - name: zero-sum
    elements:
    - label: Provisional cover image
      description: lnk.to page
      url: https://lnk.to/tricktaking_CD
  - name: fool
    elements:
    - label: Provisional cover image
      description: lnk.to page
      url: https://lnk.to/tricktaking_CD
  - name: moon
    elements:
    - label: Provisional cover image
      description: lnk.to page
      url: https://lnk.to/tricktaking_CD
  - name: EXCLAMAT!ON
    elements:
    - label: Cover image
      description: YouTube community post
      url: https://www.youtube.com/post/Ugkx0AQkkFZtBcrkKnhuMQF2ougpm9YttR4V
  - name: TR!CK TAK!NG
    elements:
    - label: Provisional cover image
      description: lnk.to page
      url: https://lnk.to/tricktaking_CD

- name: Concerts
  pages:
  - name: 1ST ONE MAN LIVE
    elements:
    - label: Cover image
      description: YouTube community post
      url: https://www.youtube.com/post/UgkxqAnpOEvogdg4EMucH3hcBmjSn7Ni-HRP
  - name: 2ND ONE MAN LIVE
    elements:
    - label: Cover image
      description: YouTube community post
      url: https://www.youtube.com/post/Ugkx5I23I_aXRlyaHsms6FAXsa5vBVWh75ov
  - name: DEBUT YEAR LAST LIVE
    elements:
    - label: Cover image
      description: YouTube community post
      url: https://www.youtube.com/post/UgkxN98F0TKTVvrIEjOwImebxf9eY3bA7c4-
  - name: 1st ONE MAN TOUR "TR!CK TAK!NG" - Osaka
    elements:
    - label: Cover image
      description: YouTube community post
      url: https://www.youtube.com/post/Ugkx-xs2wknVMbApQ9Rc1zmnyi1YCqzhYOtD
  - name: 1st ONE MAN TOUR "TR!CK TAK!NG" - Aichi
    elements:
    - label: Cover image
      description: YouTube community post
      url: https://www.youtube.com/post/Ugkx-xs2wknVMbApQ9Rc1zmnyi1YCqzhYOtD
  - name: 1st ONE MAN TOUR "TR!CK TAK!NG" - Tokyo
    elements:
    - label: Cover image
      description: YouTube community post
      url: https://www.youtube.com/post/Ugkx-xs2wknVMbApQ9Rc1zmnyi1YCqzhYOtD



