name: Publishing to GitHub Pages
on:
  push:
    branches:
    - main
jobs:
  build-upload:
    runs-on: ubuntu-latest
    env:
      CONFIG_KEY: PROD
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout fan-resources
        uses: actions/checkout@v4
        with:
          repository: skyluc/fan-resources
          token: ${{ secrets.FR_PAT }} 
          path: fan-resources
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
          cache: sbt
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - name: Build and Generate site
        run: sbt run
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # upload entire directory
          path: 'target/site'

  # Deployment job
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build-upload
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4